### ISSUE TITLE
Missing trimesh, torch module

### ISSUE THREAD

**Issue by AndreiRoibu** [papagiannakis/Elements#29]
When attempting to run the _ECSSceneClassificationExample.ipynb_ m the following missing module error is produced, despite installing everything as instructed. It is possible these packages are missing from the setup and setup config files.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 5
      3 sys.path.append("../../../")
      4 import numpy as np
----> 5 import Elements.pyECSS.utilities as util
      6 from Elements.pyGLV.GL.GameObject import GameObject
      7 from Elements.pyECSS.Component import BasicTransform, RenderMesh

File ~/Elements/Elements/pyECSS/utilities.py:20
     18 # Python external modules
     19 import numpy as np
---> 20 from trimesh import Scene
     23 # vector, points related functions -----------------------------------------------
     24 def vec(*iterable):

ModuleNotFoundError: No module named 'trimesh'
```

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 27
     25 from OpenGL.GL import GL_LINES
     26 from CreateScenes import CreateRoomScene,CreateORScene,CreatePaperScene
---> 27 import Converter
     28 import torch

File ~/Elements/Elements/pyGLV/examples/Converter.py:4
      1 import pickle
      3 import numpy as np
----> 4 import torch
      6 from atlas.model import MODEL_LIST
      7 from Elements.pyECSS.Component import RenderMesh, BasicTransform

ModuleNotFoundError: No module named 'torch'
```

Indeed, when running a `conda list` on the created environment, these are missing. Simply calling the following seems to solve the issue, but still thought raising it would be beneficial.

`conda install -c conda-forge trimesh`

& 

`conda install pytorch::pytorch torchvision torchaudio -c pytorch`

**Comment by kamarianakis** [comment]
Dear @AndreiRoibu, thanks for pointing out, the respective comment on top of respective classification example 11, points to the [respective file](https://github.com/papagiannakis/Elements/blob/develop/Elements/pyGLV/examples/requirements_example_11.md?plain=1 ) that indeed suggests installing pytorch from a specific source. I just added the respective commands to the jupyter notebook on the respective feature branch!
